name: Pflichtenheft
on:
  push:
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2


      - name: Install Latex
        run: |
          sudo apt-get install texlive texlive-lang-german texlive-latex-extra 
          sudo apt-get install texlive-base 

      - name: Where am I 
        run: |
          pwd
          ls -a

      - name: Compile LaTeX document
        run: |
          cd ./docs/Pflichtenheft/
          pdflatex -synctex=1 -interaction=nonstopmode "Pflichtenheft.tex" 
          makeindex -s nomencl.ist -o Pflichtenheft.nls Pflichtenheft.nlo
          pdflatex -synctex=1 -interaction=nonstopmode "Pflichtenheft.tex" 
          cd ../..        
          cp ./docs/Pflichtenheft/Pflichtenheft.pdf ./Pflichtenheft.pdf

      - name: Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: ./docs/Pflichtenheft/Pflichtenheft.pdf

      - name: X-FAB Upload
        run: |
          python upload.py ./Pflichtenheft.pdf
        env:
          key: ${{ secrets.FTP_PASSWORD }}
          user: ${{ secrets.FTP_USER }}
          server: ${{ secrets.FTP_SERVER }}

      - name: Clean Git
        run: |
          git clean -fX 